# Generated by Django 4.2.26 on 2025-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(null=True)),
                ('correo_electronico', models.EmailField(max_length=254, null=True)),
                ('fecha_de_nacimiento', models.DateField(null=True)),
                ('ciudad', models.CharField(max_length=20, null=True)),
                ('programa', models.DateField(null=True)),
            ],
        ),
    ]
