# Generated by Django 4.2.26 on 2025-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
