# Generated by Django 4.2.26 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
