# Generated by Django 4.2.26 on 2025-12-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='nivel_educativo',
            field=models.CharField(choices=[('PRE', 'Pregrado'), ('TEC', 'Tecnico'), ('TEG', 'Tecnologo'), ('ESP', 'Especializacion'), ('MAE', 'Maestria'), ('DOC', 'Doctorado')], default='MAE', max_length=3),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('PA', 'Pasaporte')], default='CC', max_length=3),
        ),
    ]
